// <auto-generated />
using System;
using InnowiseTask.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InnowiseTask.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220421134238_InitData")]
    partial class InitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("FridgeModelId");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ceb4d63-4def-4296-978d-91d74ab59208"),
                            FridgeModelId = new Guid("b5fcaba7-1ce1-4cd6-b4bc-f3ca970eb46c"),
                            Name = "Fridge1",
                            OwnerName = "Owner1"
                        },
                        new
                        {
                            Id = new Guid("1f05de3d-a6a7-4479-a662-b2f365d656ce"),
                            FridgeModelId = new Guid("b5fcaba7-1ce1-4cd6-b4bc-f3ca970eb46c"),
                            Name = "Fridge2",
                            OwnerName = "Owner2"
                        },
                        new
                        {
                            Id = new Guid("a75c18d9-a2b6-42cd-94d7-cc73f5afbf44"),
                            FridgeModelId = new Guid("b61ac0b1-727c-41a6-846e-db2a66338c8b"),
                            Name = "Fridge3",
                            OwnerName = "Owner3"
                        },
                        new
                        {
                            Id = new Guid("356c09b5-d03b-4d86-aaba-c59e6937c0cf"),
                            FridgeModelId = new Guid("919f36a2-0586-44e9-a67d-47d7bd519c79"),
                            Name = "Fridge4",
                            OwnerName = "Owner4"
                        },
                        new
                        {
                            Id = new Guid("e15e5293-8204-4cdb-a79a-af8ca565b99e"),
                            FridgeModelId = new Guid("da5e110c-ab38-408a-ac8a-3968f453eba8"),
                            Name = "Fridge5",
                            OwnerName = "Owner5"
                        },
                        new
                        {
                            Id = new Guid("1a749ddb-dde7-4141-8130-3eb5b517a6ab"),
                            FridgeModelId = new Guid("da5e110c-ab38-408a-ac8a-3968f453eba8"),
                            Name = "Fridge6",
                            OwnerName = "Owner6"
                        },
                        new
                        {
                            Id = new Guid("cf4ae0ba-b055-4f64-bc41-9811eaaa7280"),
                            FridgeModelId = new Guid("1fa04ca1-36b4-4fc5-afaf-f712204e3808"),
                            Name = "Fridge7",
                            OwnerName = "Owner7"
                        },
                        new
                        {
                            Id = new Guid("86563649-951a-4a02-be1b-8f07ef0a3ede"),
                            FridgeModelId = new Guid("64850365-1246-4340-8d84-64af8ce8a84b"),
                            Name = "Fridge8",
                            OwnerName = "Owner8"
                        },
                        new
                        {
                            Id = new Guid("4c086779-212e-4864-be35-6749f4ee47cd"),
                            FridgeModelId = new Guid("64850365-1246-4340-8d84-64af8ce8a84b"),
                            Name = "Fridge9",
                            OwnerName = "Owner9"
                        });
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FridgeModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("919f36a2-0586-44e9-a67d-47d7bd519c79"),
                            Name = "Liebherr",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("b5fcaba7-1ce1-4cd6-b4bc-f3ca970eb46c"),
                            Name = "Gorenje",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("b61ac0b1-727c-41a6-846e-db2a66338c8b"),
                            Name = "Samsung",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("4a013797-a6de-446a-9fca-9a2550f249d5"),
                            Name = "Snaige",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("da5e110c-ab38-408a-ac8a-3968f453eba8"),
                            Name = "LG",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("ff16208a-846a-4777-a1b1-906033ab2be7"),
                            Name = "LIBERTY",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("1fa04ca1-36b4-4fc5-afaf-f712204e3808"),
                            Name = "Bosch",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("75548054-31ea-432c-b12f-191f0c3a7924"),
                            Name = "Electrolux",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("64850365-1246-4340-8d84-64af8ce8a84b"),
                            Name = "Smeg",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.FridgeProduct", b =>
                {
                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FridgeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("FridgeProducts");

                    b.HasData(
                        new
                        {
                            FridgeId = new Guid("2ceb4d63-4def-4296-978d-91d74ab59208"),
                            ProductId = new Guid("e5f23484-9191-4101-9ced-60c771b367bf"),
                            Id = new Guid("458f0692-8ad3-45ce-9733-483e14579f9b"),
                            Quantity = 1
                        },
                        new
                        {
                            FridgeId = new Guid("2ceb4d63-4def-4296-978d-91d74ab59208"),
                            ProductId = new Guid("0ca04ea8-ea69-457d-b564-9070492bd444"),
                            Id = new Guid("34b49f1a-6eca-4744-8d88-eaf1b3c38ec1"),
                            Quantity = 10
                        },
                        new
                        {
                            FridgeId = new Guid("1f05de3d-a6a7-4479-a662-b2f365d656ce"),
                            ProductId = new Guid("0ca04ea8-ea69-457d-b564-9070492bd444"),
                            Id = new Guid("623b645c-a579-4ae1-9960-3b3a3dc00941"),
                            Quantity = 10
                        },
                        new
                        {
                            FridgeId = new Guid("1f05de3d-a6a7-4479-a662-b2f365d656ce"),
                            ProductId = new Guid("e5f23484-9191-4101-9ced-60c771b367bf"),
                            Id = new Guid("1c7906a9-26aa-48c7-9dd6-65c087ddbb1b"),
                            Quantity = 2
                        },
                        new
                        {
                            FridgeId = new Guid("1f05de3d-a6a7-4479-a662-b2f365d656ce"),
                            ProductId = new Guid("24d601bc-965f-457f-ae2e-5bf34afcba8b"),
                            Id = new Guid("0cad8a9d-7f5e-40f9-8af1-88ad88b4703e"),
                            Quantity = 2
                        },
                        new
                        {
                            FridgeId = new Guid("a75c18d9-a2b6-42cd-94d7-cc73f5afbf44"),
                            ProductId = new Guid("24d601bc-965f-457f-ae2e-5bf34afcba8b"),
                            Id = new Guid("b0fa869b-f73e-479e-b81c-1c71dcbca044"),
                            Quantity = 0
                        },
                        new
                        {
                            FridgeId = new Guid("a75c18d9-a2b6-42cd-94d7-cc73f5afbf44"),
                            ProductId = new Guid("b7c5ef3a-4132-4d10-8a9d-782ebc524af9"),
                            Id = new Guid("35a3a4dd-7737-4694-98c1-9ff94067c02a"),
                            Quantity = 10
                        },
                        new
                        {
                            FridgeId = new Guid("356c09b5-d03b-4d86-aaba-c59e6937c0cf"),
                            ProductId = new Guid("b7c5ef3a-4132-4d10-8a9d-782ebc524af9"),
                            Id = new Guid("835b284c-f178-4e53-b5f5-5dd7bbbc446d"),
                            Quantity = 10
                        },
                        new
                        {
                            FridgeId = new Guid("356c09b5-d03b-4d86-aaba-c59e6937c0cf"),
                            ProductId = new Guid("8186ec59-231a-4a94-a589-584e48ee567a"),
                            Id = new Guid("0c11c4d2-94c7-4a10-91f1-af6db6a6b28b"),
                            Quantity = 1
                        },
                        new
                        {
                            FridgeId = new Guid("356c09b5-d03b-4d86-aaba-c59e6937c0cf"),
                            ProductId = new Guid("2888dc78-ae37-4a63-a09a-b3b356b47dd4"),
                            Id = new Guid("fc3ec0bf-1550-4ff0-94cc-28c810607e8f"),
                            Quantity = 1
                        },
                        new
                        {
                            FridgeId = new Guid("356c09b5-d03b-4d86-aaba-c59e6937c0cf"),
                            ProductId = new Guid("f428d3b7-d5ae-4ada-8944-1d4a2e433238"),
                            Id = new Guid("e23cefa3-1649-4237-8ef0-335405324784"),
                            Quantity = 10
                        },
                        new
                        {
                            FridgeId = new Guid("e15e5293-8204-4cdb-a79a-af8ca565b99e"),
                            ProductId = new Guid("3cd8e973-320d-410d-889a-8522767b6549"),
                            Id = new Guid("ed0438a8-f6ed-4a90-a5c3-9cb79784df95"),
                            Quantity = 5
                        },
                        new
                        {
                            FridgeId = new Guid("e15e5293-8204-4cdb-a79a-af8ca565b99e"),
                            ProductId = new Guid("8f4dda36-4be7-4ebb-9a09-51448de3ec92"),
                            Id = new Guid("393d1430-bb04-4bdc-96f2-7378e8b3c8a0"),
                            Quantity = 6
                        },
                        new
                        {
                            FridgeId = new Guid("1a749ddb-dde7-4141-8130-3eb5b517a6ab"),
                            ProductId = new Guid("8f4dda36-4be7-4ebb-9a09-51448de3ec92"),
                            Id = new Guid("2074bea9-3170-4f00-bfe3-e1a3e0ee62b2"),
                            Quantity = 1
                        },
                        new
                        {
                            FridgeId = new Guid("1a749ddb-dde7-4141-8130-3eb5b517a6ab"),
                            ProductId = new Guid("8186ec59-231a-4a94-a589-584e48ee567a"),
                            Id = new Guid("4b64f678-6c15-49c7-87bb-ce573e59e07c"),
                            Quantity = 3
                        },
                        new
                        {
                            FridgeId = new Guid("cf4ae0ba-b055-4f64-bc41-9811eaaa7280"),
                            ProductId = new Guid("24d601bc-965f-457f-ae2e-5bf34afcba8b"),
                            Id = new Guid("28363779-84e7-4e3f-9594-9b5ba036961c"),
                            Quantity = 1
                        },
                        new
                        {
                            FridgeId = new Guid("cf4ae0ba-b055-4f64-bc41-9811eaaa7280"),
                            ProductId = new Guid("2888dc78-ae37-4a63-a09a-b3b356b47dd4"),
                            Id = new Guid("c49f01a9-87e3-471e-aec3-7baabfb70a77"),
                            Quantity = 1
                        },
                        new
                        {
                            FridgeId = new Guid("cf4ae0ba-b055-4f64-bc41-9811eaaa7280"),
                            ProductId = new Guid("0ca04ea8-ea69-457d-b564-9070492bd444"),
                            Id = new Guid("d82d249d-3650-47c4-8fbb-808fbe2bee7f"),
                            Quantity = 10
                        },
                        new
                        {
                            FridgeId = new Guid("86563649-951a-4a02-be1b-8f07ef0a3ede"),
                            ProductId = new Guid("2888dc78-ae37-4a63-a09a-b3b356b47dd4"),
                            Id = new Guid("9711181f-3bda-469d-86be-7ed393f44512"),
                            Quantity = 0
                        },
                        new
                        {
                            FridgeId = new Guid("86563649-951a-4a02-be1b-8f07ef0a3ede"),
                            ProductId = new Guid("24d601bc-965f-457f-ae2e-5bf34afcba8b"),
                            Id = new Guid("06e898eb-c594-4177-83ea-6bd71ca840c1"),
                            Quantity = 0
                        },
                        new
                        {
                            FridgeId = new Guid("86563649-951a-4a02-be1b-8f07ef0a3ede"),
                            ProductId = new Guid("8186ec59-231a-4a94-a589-584e48ee567a"),
                            Id = new Guid("d67c92b1-444a-4816-b376-1c10d6863874"),
                            Quantity = 1
                        },
                        new
                        {
                            FridgeId = new Guid("86563649-951a-4a02-be1b-8f07ef0a3ede"),
                            ProductId = new Guid("e5f23484-9191-4101-9ced-60c771b367bf"),
                            Id = new Guid("86e1b250-c4f6-4e62-a0c3-034d8020df1e"),
                            Quantity = 1
                        },
                        new
                        {
                            FridgeId = new Guid("4c086779-212e-4864-be35-6749f4ee47cd"),
                            ProductId = new Guid("8f4dda36-4be7-4ebb-9a09-51448de3ec92"),
                            Id = new Guid("cb9f59b5-751e-42a5-8cc2-8cd1259572e9"),
                            Quantity = 3
                        },
                        new
                        {
                            FridgeId = new Guid("4c086779-212e-4864-be35-6749f4ee47cd"),
                            ProductId = new Guid("3cd8e973-320d-410d-889a-8522767b6549"),
                            Id = new Guid("8953841e-2154-4bf8-a913-86983e6017d3"),
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DefaultQuantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f23484-9191-4101-9ced-60c771b367bf"),
                            DefaultQuantity = 2,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("8f4dda36-4be7-4ebb-9a09-51448de3ec92"),
                            DefaultQuantity = 3,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = new Guid("3cd8e973-320d-410d-889a-8522767b6549"),
                            DefaultQuantity = 3,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = new Guid("8186ec59-231a-4a94-a589-584e48ee567a"),
                            DefaultQuantity = 1,
                            Name = "Cola"
                        },
                        new
                        {
                            Id = new Guid("24d601bc-965f-457f-ae2e-5bf34afcba8b"),
                            DefaultQuantity = 1,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = new Guid("0ca04ea8-ea69-457d-b564-9070492bd444"),
                            DefaultQuantity = 10,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = new Guid("2888dc78-ae37-4a63-a09a-b3b356b47dd4"),
                            DefaultQuantity = 1,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("f428d3b7-d5ae-4ada-8944-1d4a2e433238"),
                            DefaultQuantity = 10,
                            Name = "Ice"
                        },
                        new
                        {
                            Id = new Guid("b7c5ef3a-4132-4d10-8a9d-782ebc524af9"),
                            DefaultQuantity = 10,
                            Name = "Mushroom"
                        });
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.Fridge", b =>
                {
                    b.HasOne("InnowiseTask.Server.Data.Models.FridgeModel", "FridgeModel")
                        .WithMany("Fridges")
                        .HasForeignKey("FridgeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeModel");
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.FridgeProduct", b =>
                {
                    b.HasOne("InnowiseTask.Server.Data.Models.Fridge", "Fridge")
                        .WithMany()
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnowiseTask.Server.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.FridgeModel", b =>
                {
                    b.Navigation("Fridges");
                });
#pragma warning restore 612, 618
        }
    }
}
