// <auto-generated />
using System;
using InnowiseTask.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InnowiseTask.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220602104727_Add_User_Entity")]
    partial class Add_User_Entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("FridgeModelId");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ceb4d63-4def-4296-978d-91d74ab59208"),
                            FridgeModelId = new Guid("b5fcaba7-1ce1-4cd6-b4bc-f3ca970eb46c"),
                            Name = "Fridge1",
                            OwnerName = "Owner1"
                        },
                        new
                        {
                            Id = new Guid("1f05de3d-a6a7-4479-a662-b2f365d656ce"),
                            FridgeModelId = new Guid("b5fcaba7-1ce1-4cd6-b4bc-f3ca970eb46c"),
                            Name = "Fridge2",
                            OwnerName = "Owner2"
                        },
                        new
                        {
                            Id = new Guid("a75c18d9-a2b6-42cd-94d7-cc73f5afbf44"),
                            FridgeModelId = new Guid("b61ac0b1-727c-41a6-846e-db2a66338c8b"),
                            Name = "Fridge3",
                            OwnerName = "Owner3"
                        },
                        new
                        {
                            Id = new Guid("356c09b5-d03b-4d86-aaba-c59e6937c0cf"),
                            FridgeModelId = new Guid("919f36a2-0586-44e9-a67d-47d7bd519c79"),
                            Name = "Fridge4",
                            OwnerName = "Owner4"
                        },
                        new
                        {
                            Id = new Guid("e15e5293-8204-4cdb-a79a-af8ca565b99e"),
                            FridgeModelId = new Guid("da5e110c-ab38-408a-ac8a-3968f453eba8"),
                            Name = "Fridge5",
                            OwnerName = "Owner5"
                        },
                        new
                        {
                            Id = new Guid("1a749ddb-dde7-4141-8130-3eb5b517a6ab"),
                            FridgeModelId = new Guid("da5e110c-ab38-408a-ac8a-3968f453eba8"),
                            Name = "Fridge6",
                            OwnerName = "Owner6"
                        },
                        new
                        {
                            Id = new Guid("cf4ae0ba-b055-4f64-bc41-9811eaaa7280"),
                            FridgeModelId = new Guid("1fa04ca1-36b4-4fc5-afaf-f712204e3808"),
                            Name = "Fridge7",
                            OwnerName = "Owner7"
                        },
                        new
                        {
                            Id = new Guid("86563649-951a-4a02-be1b-8f07ef0a3ede"),
                            FridgeModelId = new Guid("64850365-1246-4340-8d84-64af8ce8a84b"),
                            Name = "Fridge8",
                            OwnerName = "Owner8"
                        },
                        new
                        {
                            Id = new Guid("4c086779-212e-4864-be35-6749f4ee47cd"),
                            FridgeModelId = new Guid("64850365-1246-4340-8d84-64af8ce8a84b"),
                            Name = "Fridge9",
                            OwnerName = "Owner9"
                        });
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FridgeModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("919f36a2-0586-44e9-a67d-47d7bd519c79"),
                            Name = "Liebherr",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("b5fcaba7-1ce1-4cd6-b4bc-f3ca970eb46c"),
                            Name = "Gorenje",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("b61ac0b1-727c-41a6-846e-db2a66338c8b"),
                            Name = "Samsung",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("4a013797-a6de-446a-9fca-9a2550f249d5"),
                            Name = "Snaige",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("da5e110c-ab38-408a-ac8a-3968f453eba8"),
                            Name = "LG",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("ff16208a-846a-4777-a1b1-906033ab2be7"),
                            Name = "LIBERTY",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("1fa04ca1-36b4-4fc5-afaf-f712204e3808"),
                            Name = "Bosch",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("75548054-31ea-432c-b12f-191f0c3a7924"),
                            Name = "Electrolux",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("64850365-1246-4340-8d84-64af8ce8a84b"),
                            Name = "Smeg",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.FridgeProduct", b =>
                {
                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FridgeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("FridgeProducts");
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DefaultQuantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f23484-9191-4101-9ced-60c771b367bf"),
                            DefaultQuantity = 2,
                            Image = "https://images.immediate.co.uk/production/volatile/sites/30/2020/02/Glass-and-bottle-of-milk-fe0997a.jpg?quality=90&resize=960,872",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("8f4dda36-4be7-4ebb-9a09-51448de3ec92"),
                            DefaultQuantity = 3,
                            Image = "https://media.istockphoto.com/photos/orange-picture-id185284489?k=20&m=185284489&s=612x612&w=0&h=LLY2os0YTG2uAzpBKpQZOAC4DGiXBt1jJrltErTJTKI=",
                            Name = "Orange"
                        },
                        new
                        {
                            Id = new Guid("3cd8e973-320d-410d-889a-8522767b6549"),
                            DefaultQuantity = 3,
                            Image = "https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg",
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = new Guid("8186ec59-231a-4a94-a589-584e48ee567a"),
                            DefaultQuantity = 1,
                            Image = "https://media.istockphoto.com/photos/coke-picture-id458464735",
                            Name = "Cola"
                        },
                        new
                        {
                            Id = new Guid("24d601bc-965f-457f-ae2e-5bf34afcba8b"),
                            DefaultQuantity = 1,
                            Image = "https://media.istockphoto.com/photos/assortment-of-meat-and-seafood-picture-id1212824120?k=20&m=1212824120&s=612x612&w=0&h=yHkNBM-cUaMXEdVQj1GzZ_AAZ9tsV06dMuYIzcRzqbM=",
                            Name = "Meat"
                        },
                        new
                        {
                            Id = new Guid("0ca04ea8-ea69-457d-b564-9070492bd444"),
                            DefaultQuantity = 10,
                            Image = "https://cdn.britannica.com/94/151894-050-F72A5317/Brown-eggs.jpg",
                            Name = "Egg"
                        },
                        new
                        {
                            Id = new Guid("2888dc78-ae37-4a63-a09a-b3b356b47dd4"),
                            DefaultQuantity = 1,
                            Image = "https://ychef.files.bbci.co.uk/976x549/p091595d.jpg",
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("f428d3b7-d5ae-4ada-8944-1d4a2e433238"),
                            DefaultQuantity = 10,
                            Image = "https://media.istockphoto.com/photos/ice-cubes-picture-id177131518?k=20&m=177131518&s=612x612&w=0&h=Bym7fbnY-eOI0CvFJhPJv_B4uLhTjul4ThN05p_Eao0=",
                            Name = "Ice"
                        },
                        new
                        {
                            Id = new Guid("b7c5ef3a-4132-4d10-8a9d-782ebc524af9"),
                            DefaultQuantity = 10,
                            Image = "https://cdn-prod.medicalnewstoday.com/content/images/articles/278/278858/mushrooms-in-a-bowel-on-a-dark-table.jpg",
                            Name = "Mushroom"
                        });
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8c2f458-16f7-41fd-8f2f-dd8e717d0997"),
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.Fridge", b =>
                {
                    b.HasOne("InnowiseTask.Server.Data.Models.FridgeModel", "FridgeModel")
                        .WithMany("Fridges")
                        .HasForeignKey("FridgeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeModel");
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.FridgeProduct", b =>
                {
                    b.HasOne("InnowiseTask.Server.Data.Models.Fridge", "Fridge")
                        .WithMany("FridgeProducts")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InnowiseTask.Server.Data.Models.Product", "Product")
                        .WithMany("FridgeProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.Fridge", b =>
                {
                    b.Navigation("FridgeProducts");
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.FridgeModel", b =>
                {
                    b.Navigation("Fridges");
                });

            modelBuilder.Entity("InnowiseTask.Server.Data.Models.Product", b =>
                {
                    b.Navigation("FridgeProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
